receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4319"

exporters:
  otlp:
    endpoint: "localhost:14250"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]